// <auto-generated />
using System;
using AppCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppCore.Migrations
{
    [DbContext(typeof(BirdTrainingCenterSystemContext))]
    partial class BirdTrainingCenterSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.Entities.AcquirableSkill", b =>
                {
                    b.Property<int>("BirdSpeciesId")
                        .HasColumnType("integer");

                    b.Property<int>("BirdSkillId")
                        .HasColumnType("integer");

                    b.Property<string>("Condition")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.HasKey("BirdSpeciesId", "BirdSkillId")
                        .HasName("PK__Acquirab__4802579E7110A6F8");

                    b.HasIndex("BirdSkillId");

                    b.ToTable("AcquirableSkill", (string)null);
                });

            modelBuilder.Entity("Models.Entities.AdditionalConsultingBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsultingTicketId")
                        .HasColumnType("integer");

                    b.Property<string>("Evidence")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("ConsultingTicketId");

                    b.ToTable("AdditionalConsultingBill", (string)null);
                });

            modelBuilder.Entity("Models.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressDetail")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("Models.Entities.Bird", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BirdSpeciesId")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Picture")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("BirdSpeciesId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Bird", (string)null);
                });

            modelBuilder.Entity("Models.Entities.BirdCertificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BirdCenterName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Picture")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShortDescrption")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("TrainingCourseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrainingCourseId");

                    b.ToTable("BirdCertificate", (string)null);
                });

            modelBuilder.Entity("Models.Entities.BirdCertificateDetail", b =>
                {
                    b.Property<int>("BirdId")
                        .HasColumnType("integer");

                    b.Property<int>("BirdCertificateId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReceiveDate")
                        .HasColumnType("date");

                    b.HasKey("BirdId", "BirdCertificateId")
                        .HasName("PK__BirdCert__CB94077CBC6D69F2");

                    b.HasIndex("BirdCertificateId");

                    b.ToTable("BirdCertificateDetail", (string)null);
                });

            modelBuilder.Entity("Models.Entities.BirdCertificateSkill", b =>
                {
                    b.Property<int>("BirdSkillId")
                        .HasColumnType("integer");

                    b.Property<int>("BirdCertificateId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("date");

                    b.HasKey("BirdSkillId", "BirdCertificateId")
                        .HasName("PK__BirdCert__A080D86A5033BEFE");

                    b.HasIndex("BirdCertificateId");

                    b.ToTable("BirdCertificateSkill", (string)null);
                });

            modelBuilder.Entity("Models.Entities.BirdSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("BirdSkill", (string)null);
                });

            modelBuilder.Entity("Models.Entities.BirdSpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShortDetail")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("BirdSpecies");
                });

            modelBuilder.Entity("Models.Entities.BirdTrainingCourse", b =>
                {
                    b.Property<int>("BirdId")
                        .HasColumnType("integer");

                    b.Property<int>("TrainingCourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ActualDateReturn")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ActualStartDate")
                        .HasColumnType("date");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateReceivedBird")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ExpectedDateReturn")
                        .HasColumnType("date");

                    b.Property<DateTime?>("ExpectedStartDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("LastestUpdate")
                        .HasColumnType("date");

                    b.Property<string>("ReceiveNote")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ReceivePicture")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ReturnNote")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ReturnPicture")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("StaffId")
                        .HasColumnType("integer");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("numeric(19,0)");

                    b.Property<DateTime?>("TrainingDoneDate")
                        .HasColumnType("date");

                    b.HasKey("BirdId", "TrainingCourseId")
                        .HasName("PK__Bird_Tra__9B81A2E61F9D5140");

                    b.HasIndex("StaffId");

                    b.HasIndex("TrainingCourseId");

                    b.ToTable("Bird_TrainingCourse", (string)null);
                });

            modelBuilder.Entity("Models.Entities.BirdTrainingProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BirdId")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<int>("TrainerId")
                        .HasColumnType("integer");

                    b.Property<int>("TrainingCourseId")
                        .HasColumnType("integer");

                    b.Property<int>("TrainingCourseSkillId")
                        .HasColumnType("integer")
                        .HasColumnName("TrainingCourse_SkillId");

                    b.Property<DateTime?>("TrainingDoneDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.HasIndex("BirdId", "TrainingCourseId");

                    b.HasIndex("TrainingCourseId", "TrainingCourseSkillId");

                    b.ToTable("Bird_TrainingProgress", (string)null);
                });

            modelBuilder.Entity("Models.Entities.BirdTrainingReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BirdId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("date");

                    b.Property<float?>("Progress")
                        .HasColumnType("real");

                    b.Property<int>("TrainerId")
                        .HasColumnType("integer");

                    b.Property<int>("TrainingCourseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.HasIndex("BirdId", "TrainingCourseId");

                    b.ToTable("BirdTrainingReport", (string)null);
                });

            modelBuilder.Entity("Models.Entities.CenterSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("date");

                    b.Property<int>("SlotId")
                        .HasColumnType("integer");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SlotId");

                    b.ToTable("CenterSlot", (string)null);
                });

            modelBuilder.Entity("Models.Entities.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BirdCenterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OnlineCourseId")
                        .HasColumnType("integer");

                    b.Property<string>("Picture")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShortDescrption")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("OnlineCourseId");

                    b.ToTable("Certificate", (string)null);
                });

            modelBuilder.Entity("Models.Entities.ConsultingPricePolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("OnlineOrOffline")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Price")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.ToTable("ConsultingPricePolicy", (string)null);
                });

            modelBuilder.Entity("Models.Entities.ConsultingTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualEndSlot")
                        .HasColumnType("integer");

                    b.Property<int?>("ActualSlotStart")
                        .HasColumnType("integer");

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<string>("ConsultingDetail")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ConsultingPricePolicyId")
                        .HasColumnType("integer");

                    b.Property<int>("ConsultingTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int?>("Distance")
                        .HasColumnType("integer");

                    b.Property<int>("DistancePriceId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpectedDate")
                        .HasColumnType("date");

                    b.Property<int?>("ExpectedSlotEnd")
                        .HasColumnType("integer");

                    b.Property<int?>("ExpectedSlotStart")
                        .HasColumnType("integer");

                    b.Property<string>("GgMeetLink")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<bool?>("OnlineOrOffline")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Price")
                        .HasColumnType("money");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TrainerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ConsultingPricePolicyId");

                    b.HasIndex("ConsultingTypeId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DistancePriceId");

                    b.HasIndex("TrainerId");

                    b.ToTable("ConsultingTicket", (string)null);
                });

            modelBuilder.Entity("Models.Entities.ConsultingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("ConsultingType", (string)null);
                });

            modelBuilder.Entity("Models.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDay")
                        .HasColumnType("date");

                    b.Property<bool?>("Gender")
                        .HasColumnType("boolean");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("Models.Entities.CustomerCertificateDetail", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("CertificateId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReceiveDate")
                        .HasColumnType("date");

                    b.HasKey("CustomerId", "CertificateId")
                        .HasName("PK__Customer__AF11EEA46480DD5B");

                    b.HasIndex("CertificateId");

                    b.ToTable("Customer_CertificateDetail", (string)null);
                });

            modelBuilder.Entity("Models.Entities.CustomerLessonDetail", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("LessionId")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsComplete")
                        .HasColumnType("boolean");

                    b.HasKey("CustomerId", "LessionId")
                        .HasName("PK__Customer__304EA374927079B2");

                    b.HasIndex("LessionId");

                    b.ToTable("Customer_LessonDetail", (string)null);
                });

            modelBuilder.Entity("Models.Entities.CustomerOnlineCourseDetail", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("OnlineCourseId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Price")
                        .HasColumnType("money");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.HasKey("CustomerId", "OnlineCourseId")
                        .HasName("PK__Customer__FFA1E3B7B9E3B84E");

                    b.HasIndex("OnlineCourseId");

                    b.ToTable("Customer_OnlineCourseDetail", (string)null);
                });

            modelBuilder.Entity("Models.Entities.CustomerSectionDetail", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("SectionId")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsComplete")
                        .HasColumnType("boolean");

                    b.HasKey("CustomerId", "SectionId")
                        .HasName("PK__Customer__9CA0945FC3C11C0A");

                    b.HasIndex("SectionId");

                    b.ToTable("Customer_SectionDetail", (string)null);
                });

            modelBuilder.Entity("Models.Entities.CustomerWorkshopClass", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkshopClassId")
                        .HasColumnType("integer");

                    b.Property<float?>("Discount")
                        .HasColumnType("real");

                    b.Property<decimal?>("Price")
                        .HasColumnType("money");

                    b.Property<float?>("RefundRate")
                        .HasColumnType("real");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.HasKey("CustomerId", "WorkshopClassId")
                        .HasName("PK__Customer__7EEF83480B0E1741");

                    b.HasIndex("WorkshopClassId");

                    b.ToTable("Customer_WorkshopClass", (string)null);
                });

            modelBuilder.Entity("Models.Entities.DistancePrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsultingPricePolicyId")
                        .HasColumnType("integer");

                    b.Property<int?>("From")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PricePerKm")
                        .HasColumnType("money");

                    b.Property<int?>("To")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DistancePrice", (string)null);
                });

            modelBuilder.Entity("Models.Entities.EntityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("EntityType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Others"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Advice Consulting"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Workshop class"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Online Course"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Training Course"
                        });
                });

            modelBuilder.Entity("Models.Entities.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer");

                    b.Property<int>("EntityTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("FeedbackDetail")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("FeedbackTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EntityTypeId");

                    b.HasIndex("FeedbackTypeId");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("Models.Entities.FeedbackType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("FeedbackType", (string)null);
                });

            modelBuilder.Entity("Models.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Detail")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("SectionId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Video")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("Lesson", (string)null);
                });

            modelBuilder.Entity("Models.Entities.OnlineCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Picture")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("money");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.ToTable("OnlineCourse", (string)null);
                });

            modelBuilder.Entity("Models.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Models.Entities.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OnlineCourseId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("OnlineCourseId");

                    b.ToTable("Section", (string)null);
                });

            modelBuilder.Entity("Models.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Skill", (string)null);
                });

            modelBuilder.Entity("Models.Entities.Slot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.ToTable("Slot", (string)null);
                });

            modelBuilder.Entity("Models.Entities.TrainableSkill", b =>
                {
                    b.Property<int>("BirdSkillId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.HasKey("BirdSkillId", "SkillId")
                        .HasName("PK__Trainabl__707AE5004A4E9F0D");

                    b.HasIndex("SkillId");

                    b.ToTable("TrainableSkill", (string)null);
                });

            modelBuilder.Entity("Models.Entities.Trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDay")
                        .HasColumnType("date");

                    b.Property<bool?>("Gender")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsFullTime")
                        .HasColumnType("boolean");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Trainer", (string)null);
                });

            modelBuilder.Entity("Models.Entities.TrainerSkill", b =>
                {
                    b.Property<int>("TrainerId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TrainerId", "SkillId")
                        .HasName("PK__Trainer___5B901364F714CF7C");

                    b.HasIndex("SkillId");

                    b.ToTable("Trainer_Skill", (string)null);
                });

            modelBuilder.Entity("Models.Entities.TrainerSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer");

                    b.Property<int>("EntityTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SlotId")
                        .HasColumnType("integer");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TrainerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EntityTypeId");

                    b.HasIndex("SlotId");

                    b.HasIndex("TrainerId");

                    b.ToTable("TrainerSlot", (string)null);
                });

            modelBuilder.Entity("Models.Entities.TrainingCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BirdSpeciesId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Picture")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("money");

                    b.Property<int?>("TotalSlot")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BirdSpeciesId");

                    b.ToTable("TrainingCourse", (string)null);
                });

            modelBuilder.Entity("Models.Entities.TrainingCourseSkill", b =>
                {
                    b.Property<int>("TrainingCourseId")
                        .HasColumnType("integer");

                    b.Property<int>("BirdSkillId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Price")
                        .HasColumnType("money");

                    b.HasKey("TrainingCourseId", "BirdSkillId")
                        .HasName("PK__Training__4081104E95830865");

                    b.HasIndex("BirdSkillId");

                    b.ToTable("TrainingCourseSkill", (string)null);
                });

            modelBuilder.Entity("Models.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateCreate")
                        .HasColumnType("date");

                    b.Property<string>("Detail")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer");

                    b.Property<int>("EntityTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentCode")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("TotalPayment")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EntityTypeId");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("PhoneNumber")
                        .HasColumnType("numeric(18,0)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__User__A9D105343F1DA3FF")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Models.Entities.Workshop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .IsUnicode(false)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Picture")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("money");

                    b.Property<int?>("RegisterEnd")
                        .HasColumnType("integer");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("TotalSlot")
                        .HasColumnType("integer");

                    b.Property<int>("WorkshopPricePolicyId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkshopRefundPolicyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopPricePolicyId");

                    b.HasIndex("WorkshopRefundPolicyId");

                    b.ToTable("Workshop", (string)null);
                });

            modelBuilder.Entity("Models.Entities.WorkshopAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AttendDate")
                        .HasColumnType("date");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkshopClassId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("WorkshopClassId");

                    b.ToTable("WorkshopAttendance", (string)null);
                });

            modelBuilder.Entity("Models.Entities.WorkshopClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("RegisterEndDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("date");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopId");

                    b.ToTable("WorkshopClass", (string)null);
                });

            modelBuilder.Entity("Models.Entities.WorkshopClassDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DaySlotId")
                        .HasColumnType("integer");

                    b.Property<string>("Detail")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("TrainerId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkshopClassId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DaySlotId");

                    b.HasIndex("TrainerId");

                    b.HasIndex("WorkshopClassId");

                    b.ToTable("WorkshopClassDetail", (string)null);
                });

            modelBuilder.Entity("Models.Entities.WorkshopPricePolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float?>("Discount")
                        .HasColumnType("real");

                    b.Property<int?>("TotalWorkshop")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WorkshopPricePolicy", (string)null);
                });

            modelBuilder.Entity("Models.Entities.WorkshopRefundPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float?>("RefundRate")
                        .HasColumnType("real");

                    b.Property<int?>("TotalDayBeforeStart")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WorkshopRefundPolicy", (string)null);
                });

            modelBuilder.Entity("Models.Entities.AcquirableSkill", b =>
                {
                    b.HasOne("Models.Entities.BirdSkill", "BirdSkill")
                        .WithMany("AcquirableSkills")
                        .HasForeignKey("BirdSkillId")
                        .IsRequired()
                        .HasConstraintName("FKAcquirable305826");

                    b.HasOne("Models.Entities.BirdSpecies", "BirdSpecies")
                        .WithMany("AcquirableSkills")
                        .HasForeignKey("BirdSpeciesId")
                        .IsRequired()
                        .HasConstraintName("FKAcquirable80836");

                    b.Navigation("BirdSkill");

                    b.Navigation("BirdSpecies");
                });

            modelBuilder.Entity("Models.Entities.AdditionalConsultingBill", b =>
                {
                    b.HasOne("Models.Entities.ConsultingTicket", "ConsultingTicket")
                        .WithMany("AdditionalConsultingBills")
                        .HasForeignKey("ConsultingTicketId")
                        .IsRequired()
                        .HasConstraintName("FKAdditional256950");

                    b.Navigation("ConsultingTicket");
                });

            modelBuilder.Entity("Models.Entities.Address", b =>
                {
                    b.HasOne("Models.Entities.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FKAddress64774");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Models.Entities.Bird", b =>
                {
                    b.HasOne("Models.Entities.BirdSpecies", "BirdSpecies")
                        .WithMany("Birds")
                        .HasForeignKey("BirdSpeciesId")
                        .IsRequired()
                        .HasConstraintName("FKBird650663");

                    b.HasOne("Models.Entities.Customer", "Customer")
                        .WithMany("Birds")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FKBird173768");

                    b.Navigation("BirdSpecies");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Models.Entities.BirdCertificate", b =>
                {
                    b.HasOne("Models.Entities.TrainingCourse", "TrainingCourse")
                        .WithMany("BirdCertificates")
                        .HasForeignKey("TrainingCourseId")
                        .IsRequired()
                        .HasConstraintName("FKBirdCertif231604");

                    b.Navigation("TrainingCourse");
                });

            modelBuilder.Entity("Models.Entities.BirdCertificateDetail", b =>
                {
                    b.HasOne("Models.Entities.BirdCertificate", "BirdCertificate")
                        .WithMany("BirdCertificateDetails")
                        .HasForeignKey("BirdCertificateId")
                        .IsRequired()
                        .HasConstraintName("FKBirdCertif464427");

                    b.HasOne("Models.Entities.Bird", "Bird")
                        .WithMany("BirdCertificateDetails")
                        .HasForeignKey("BirdId")
                        .IsRequired()
                        .HasConstraintName("FKBirdCertif999788");

                    b.Navigation("Bird");

                    b.Navigation("BirdCertificate");
                });

            modelBuilder.Entity("Models.Entities.BirdCertificateSkill", b =>
                {
                    b.HasOne("Models.Entities.BirdCertificate", "BirdCertificate")
                        .WithMany("BirdCertificateSkills")
                        .HasForeignKey("BirdCertificateId")
                        .IsRequired()
                        .HasConstraintName("FKBirdCertif72357");

                    b.HasOne("Models.Entities.BirdSkill", "BirdSkill")
                        .WithMany("BirdCertificateSkills")
                        .HasForeignKey("BirdSkillId")
                        .IsRequired()
                        .HasConstraintName("FKBirdCertif163982");

                    b.Navigation("BirdCertificate");

                    b.Navigation("BirdSkill");
                });

            modelBuilder.Entity("Models.Entities.BirdTrainingCourse", b =>
                {
                    b.HasOne("Models.Entities.Bird", "Bird")
                        .WithMany("BirdTrainingCourses")
                        .HasForeignKey("BirdId")
                        .IsRequired()
                        .HasConstraintName("FKBird_Train718139");

                    b.HasOne("Models.Entities.User", "Staff")
                        .WithMany("BirdTrainingCourses")
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("FKBird_Train934485");

                    b.HasOne("Models.Entities.TrainingCourse", "TrainingCourse")
                        .WithMany("BirdTrainingCourses")
                        .HasForeignKey("TrainingCourseId")
                        .IsRequired()
                        .HasConstraintName("FKBird_Train368802");

                    b.Navigation("Bird");

                    b.Navigation("Staff");

                    b.Navigation("TrainingCourse");
                });

            modelBuilder.Entity("Models.Entities.BirdTrainingProgress", b =>
                {
                    b.HasOne("Models.Entities.Trainer", "Trainer")
                        .WithMany("BirdTrainingProgresses")
                        .HasForeignKey("TrainerId")
                        .IsRequired()
                        .HasConstraintName("FKBird_Train934988");

                    b.HasOne("Models.Entities.BirdTrainingCourse", "BirdTrainingCourse")
                        .WithMany("BirdTrainingProgresses")
                        .HasForeignKey("BirdId", "TrainingCourseId")
                        .IsRequired()
                        .HasConstraintName("FKBird_Train662198");

                    b.HasOne("Models.Entities.TrainingCourseSkill", "TrainingCourse")
                        .WithMany("BirdTrainingProgresses")
                        .HasForeignKey("TrainingCourseId", "TrainingCourseSkillId")
                        .IsRequired()
                        .HasConstraintName("FKBird_Train187888");

                    b.Navigation("BirdTrainingCourse");

                    b.Navigation("Trainer");

                    b.Navigation("TrainingCourse");
                });

            modelBuilder.Entity("Models.Entities.BirdTrainingReport", b =>
                {
                    b.HasOne("Models.Entities.Trainer", "Trainer")
                        .WithMany("BirdTrainingReports")
                        .HasForeignKey("TrainerId")
                        .IsRequired()
                        .HasConstraintName("FKBirdTraini332709");

                    b.HasOne("Models.Entities.BirdTrainingCourse", "BirdTrainingCourse")
                        .WithMany("BirdTrainingReports")
                        .HasForeignKey("BirdId", "TrainingCourseId")
                        .IsRequired()
                        .HasConstraintName("FKBirdTraini940080");

                    b.Navigation("BirdTrainingCourse");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Models.Entities.CenterSlot", b =>
                {
                    b.HasOne("Models.Entities.Slot", "Slot")
                        .WithMany("CenterSlots")
                        .HasForeignKey("SlotId")
                        .IsRequired()
                        .HasConstraintName("FKCenterSlot412931");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("Models.Entities.Certificate", b =>
                {
                    b.HasOne("Models.Entities.OnlineCourse", "OnlineCourse")
                        .WithMany("Certificates")
                        .HasForeignKey("OnlineCourseId")
                        .IsRequired()
                        .HasConstraintName("FKCertificat555329");

                    b.Navigation("OnlineCourse");
                });

            modelBuilder.Entity("Models.Entities.ConsultingTicket", b =>
                {
                    b.HasOne("Models.Entities.Address", "Address")
                        .WithMany("ConsultingTickets")
                        .HasForeignKey("AddressId")
                        .IsRequired()
                        .HasConstraintName("FKConsulting220553");

                    b.HasOne("Models.Entities.ConsultingPricePolicy", "ConsultingPricePolicy")
                        .WithMany("ConsultingTickets")
                        .HasForeignKey("ConsultingPricePolicyId")
                        .IsRequired()
                        .HasConstraintName("FKConsulting196354");

                    b.HasOne("Models.Entities.ConsultingType", "ConsultingType")
                        .WithMany("ConsultingTickets")
                        .HasForeignKey("ConsultingTypeId")
                        .IsRequired()
                        .HasConstraintName("FKConsulting521439");

                    b.HasOne("Models.Entities.Customer", "Customer")
                        .WithMany("ConsultingTickets")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FKConsulting154539");

                    b.HasOne("Models.Entities.DistancePrice", "DistancePrice")
                        .WithMany("ConsultingTickets")
                        .HasForeignKey("DistancePriceId")
                        .IsRequired()
                        .HasConstraintName("FKConsulting564465");

                    b.HasOne("Models.Entities.Trainer", "Trainer")
                        .WithMany("ConsultingTickets")
                        .HasForeignKey("TrainerId")
                        .IsRequired()
                        .HasConstraintName("FKConsulting31098");

                    b.Navigation("Address");

                    b.Navigation("ConsultingPricePolicy");

                    b.Navigation("ConsultingType");

                    b.Navigation("Customer");

                    b.Navigation("DistancePrice");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Models.Entities.Customer", b =>
                {
                    b.HasOne("Models.Entities.User", "User")
                        .WithMany("Customers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FKCustomer697132");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.Entities.CustomerCertificateDetail", b =>
                {
                    b.HasOne("Models.Entities.Certificate", "Certificate")
                        .WithMany("CustomerCertificateDetails")
                        .HasForeignKey("CertificateId")
                        .IsRequired()
                        .HasConstraintName("FKCustomer_C508581");

                    b.HasOne("Models.Entities.Customer", "Customer")
                        .WithMany("CustomerCertificateDetails")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FKCustomer_C859755");

                    b.Navigation("Certificate");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Models.Entities.CustomerLessonDetail", b =>
                {
                    b.HasOne("Models.Entities.Customer", "Customer")
                        .WithMany("CustomerLessonDetails")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FKCustomer_L809461");

                    b.HasOne("Models.Entities.Lesson", "Lession")
                        .WithMany("CustomerLessonDetails")
                        .HasForeignKey("LessionId")
                        .IsRequired()
                        .HasConstraintName("FKCustomer_L582869");

                    b.Navigation("Customer");

                    b.Navigation("Lession");
                });

            modelBuilder.Entity("Models.Entities.CustomerOnlineCourseDetail", b =>
                {
                    b.HasOne("Models.Entities.Customer", "Customer")
                        .WithMany("CustomerOnlineCourseDetails")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FKCustomer_O139976");

                    b.HasOne("Models.Entities.OnlineCourse", "OnlineCourse")
                        .WithMany("CustomerOnlineCourseDetails")
                        .HasForeignKey("OnlineCourseId")
                        .IsRequired()
                        .HasConstraintName("FKCustomer_O181189");

                    b.Navigation("Customer");

                    b.Navigation("OnlineCourse");
                });

            modelBuilder.Entity("Models.Entities.CustomerSectionDetail", b =>
                {
                    b.HasOne("Models.Entities.Customer", "Customer")
                        .WithMany("CustomerSectionDetails")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FKCustomer_S58540");

                    b.HasOne("Models.Entities.Section", "Section")
                        .WithMany("CustomerSectionDetails")
                        .HasForeignKey("SectionId")
                        .IsRequired()
                        .HasConstraintName("FKCustomer_S977222");

                    b.Navigation("Customer");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Models.Entities.CustomerWorkshopClass", b =>
                {
                    b.HasOne("Models.Entities.Customer", "Customer")
                        .WithMany("CustomerWorkshopClasses")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FKCustomer_W416862");

                    b.HasOne("Models.Entities.WorkshopClass", "WorkshopClass")
                        .WithMany("CustomerWorkshopClasses")
                        .HasForeignKey("WorkshopClassId")
                        .IsRequired()
                        .HasConstraintName("FKCustomer_W257990");

                    b.Navigation("Customer");

                    b.Navigation("WorkshopClass");
                });

            modelBuilder.Entity("Models.Entities.Feedback", b =>
                {
                    b.HasOne("Models.Entities.Customer", "Customer")
                        .WithMany("Feedbacks")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FKFeedback245587");

                    b.HasOne("Models.Entities.EntityType", "EntityType")
                        .WithMany("Feedbacks")
                        .HasForeignKey("EntityTypeId")
                        .IsRequired()
                        .HasConstraintName("FKFeedback674040");

                    b.HasOne("Models.Entities.FeedbackType", "FeedbackType")
                        .WithMany("Feedbacks")
                        .HasForeignKey("FeedbackTypeId")
                        .IsRequired()
                        .HasConstraintName("FKFeedback625969");

                    b.Navigation("Customer");

                    b.Navigation("EntityType");

                    b.Navigation("FeedbackType");
                });

            modelBuilder.Entity("Models.Entities.Lesson", b =>
                {
                    b.HasOne("Models.Entities.Section", "Section")
                        .WithMany("Lessons")
                        .HasForeignKey("SectionId")
                        .IsRequired()
                        .HasConstraintName("FKLesson170997");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Models.Entities.Section", b =>
                {
                    b.HasOne("Models.Entities.OnlineCourse", "OnlineCourse")
                        .WithMany("Sections")
                        .HasForeignKey("OnlineCourseId")
                        .IsRequired()
                        .HasConstraintName("FKSection929188");

                    b.Navigation("OnlineCourse");
                });

            modelBuilder.Entity("Models.Entities.TrainableSkill", b =>
                {
                    b.HasOne("Models.Entities.BirdSkill", "BirdSkill")
                        .WithMany("TrainableSkills")
                        .HasForeignKey("BirdSkillId")
                        .IsRequired()
                        .HasConstraintName("FKTrainableS485101");

                    b.HasOne("Models.Entities.Skill", "Skill")
                        .WithMany("TrainableSkills")
                        .HasForeignKey("SkillId")
                        .IsRequired()
                        .HasConstraintName("FKTrainableS574420");

                    b.Navigation("BirdSkill");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Models.Entities.Trainer", b =>
                {
                    b.HasOne("Models.Entities.User", "User")
                        .WithMany("Trainers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FKTrainer76895");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.Entities.TrainerSkill", b =>
                {
                    b.HasOne("Models.Entities.Skill", "Skill")
                        .WithMany("TrainerSkills")
                        .HasForeignKey("SkillId")
                        .IsRequired()
                        .HasConstraintName("FKTrainer_Sk368940");

                    b.HasOne("Models.Entities.Trainer", "Trainer")
                        .WithMany("TrainerSkills")
                        .HasForeignKey("TrainerId")
                        .IsRequired()
                        .HasConstraintName("FKTrainer_Sk733170");

                    b.Navigation("Skill");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Models.Entities.TrainerSlot", b =>
                {
                    b.HasOne("Models.Entities.EntityType", "EntityType")
                        .WithMany("TrainerSlots")
                        .HasForeignKey("EntityTypeId")
                        .IsRequired()
                        .HasConstraintName("FKTrainerSlo399380");

                    b.HasOne("Models.Entities.Slot", "Slot")
                        .WithMany("TrainerSlots")
                        .HasForeignKey("SlotId")
                        .IsRequired()
                        .HasConstraintName("FKTrainerSlo833189");

                    b.HasOne("Models.Entities.Trainer", "Trainer")
                        .WithMany("TrainerSlots")
                        .HasForeignKey("TrainerId")
                        .IsRequired()
                        .HasConstraintName("FKTrainerSlo815026");

                    b.Navigation("EntityType");

                    b.Navigation("Slot");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Models.Entities.TrainingCourse", b =>
                {
                    b.HasOne("Models.Entities.BirdSpecies", "BirdSpecies")
                        .WithMany("TrainingCourses")
                        .HasForeignKey("BirdSpeciesId")
                        .IsRequired()
                        .HasConstraintName("FKTrainingCo245376");

                    b.Navigation("BirdSpecies");
                });

            modelBuilder.Entity("Models.Entities.TrainingCourseSkill", b =>
                {
                    b.HasOne("Models.Entities.BirdSkill", "BirdSkill")
                        .WithMany("TrainingCourseSkills")
                        .HasForeignKey("BirdSkillId")
                        .IsRequired()
                        .HasConstraintName("FKTrainingCo551235");

                    b.HasOne("Models.Entities.TrainingCourse", "TrainingCourse")
                        .WithMany("TrainingCourseSkills")
                        .HasForeignKey("TrainingCourseId")
                        .IsRequired()
                        .HasConstraintName("FKTrainingCo866476");

                    b.Navigation("BirdSkill");

                    b.Navigation("TrainingCourse");
                });

            modelBuilder.Entity("Models.Entities.Transaction", b =>
                {
                    b.HasOne("Models.Entities.Customer", "Customer")
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FKTransactio250053");

                    b.HasOne("Models.Entities.EntityType", "EntityType")
                        .WithMany("Transactions")
                        .HasForeignKey("EntityTypeId")
                        .IsRequired()
                        .HasConstraintName("FKTransactio678506");

                    b.Navigation("Customer");

                    b.Navigation("EntityType");
                });

            modelBuilder.Entity("Models.Entities.User", b =>
                {
                    b.HasOne("Models.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FKUser349727");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Models.Entities.Workshop", b =>
                {
                    b.HasOne("Models.Entities.WorkshopPricePolicy", "WorkshopPricePolicy")
                        .WithMany("Workshops")
                        .HasForeignKey("WorkshopPricePolicyId")
                        .IsRequired()
                        .HasConstraintName("FKWorkshop893305");

                    b.HasOne("Models.Entities.WorkshopRefundPolicy", "WorkshopRefundPolicy")
                        .WithMany("Workshops")
                        .HasForeignKey("WorkshopRefundPolicyId")
                        .IsRequired()
                        .HasConstraintName("FKWorkshop234277");

                    b.Navigation("WorkshopPricePolicy");

                    b.Navigation("WorkshopRefundPolicy");
                });

            modelBuilder.Entity("Models.Entities.WorkshopAttendance", b =>
                {
                    b.HasOne("Models.Entities.Customer", "Customer")
                        .WithMany("WorkshopAttendances")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FKWorkshopAt124181");

                    b.HasOne("Models.Entities.WorkshopClass", "WorkshopClass")
                        .WithMany("WorkshopAttendances")
                        .HasForeignKey("WorkshopClassId")
                        .IsRequired()
                        .HasConstraintName("FKWorkshopAt172557");

                    b.Navigation("Customer");

                    b.Navigation("WorkshopClass");
                });

            modelBuilder.Entity("Models.Entities.WorkshopClass", b =>
                {
                    b.HasOne("Models.Entities.Workshop", "Workshop")
                        .WithMany("WorkshopClasses")
                        .HasForeignKey("WorkshopId")
                        .IsRequired()
                        .HasConstraintName("FKWorkshopCl950556");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("Models.Entities.WorkshopClassDetail", b =>
                {
                    b.HasOne("Models.Entities.TrainerSlot", "DaySlot")
                        .WithMany("WorkshopClassDetails")
                        .HasForeignKey("DaySlotId");

                    b.HasOne("Models.Entities.Trainer", null)
                        .WithMany("WorkshopClassDetails")
                        .HasForeignKey("TrainerId");

                    b.HasOne("Models.Entities.WorkshopClass", "WorkshopClass")
                        .WithMany("WorkshopClassDetails")
                        .HasForeignKey("WorkshopClassId")
                        .IsRequired();

                    b.Navigation("DaySlot");

                    b.Navigation("WorkshopClass");
                });

            modelBuilder.Entity("Models.Entities.Address", b =>
                {
                    b.Navigation("ConsultingTickets");
                });

            modelBuilder.Entity("Models.Entities.Bird", b =>
                {
                    b.Navigation("BirdCertificateDetails");

                    b.Navigation("BirdTrainingCourses");
                });

            modelBuilder.Entity("Models.Entities.BirdCertificate", b =>
                {
                    b.Navigation("BirdCertificateDetails");

                    b.Navigation("BirdCertificateSkills");
                });

            modelBuilder.Entity("Models.Entities.BirdSkill", b =>
                {
                    b.Navigation("AcquirableSkills");

                    b.Navigation("BirdCertificateSkills");

                    b.Navigation("TrainableSkills");

                    b.Navigation("TrainingCourseSkills");
                });

            modelBuilder.Entity("Models.Entities.BirdSpecies", b =>
                {
                    b.Navigation("AcquirableSkills");

                    b.Navigation("Birds");

                    b.Navigation("TrainingCourses");
                });

            modelBuilder.Entity("Models.Entities.BirdTrainingCourse", b =>
                {
                    b.Navigation("BirdTrainingProgresses");

                    b.Navigation("BirdTrainingReports");
                });

            modelBuilder.Entity("Models.Entities.Certificate", b =>
                {
                    b.Navigation("CustomerCertificateDetails");
                });

            modelBuilder.Entity("Models.Entities.ConsultingPricePolicy", b =>
                {
                    b.Navigation("ConsultingTickets");
                });

            modelBuilder.Entity("Models.Entities.ConsultingTicket", b =>
                {
                    b.Navigation("AdditionalConsultingBills");
                });

            modelBuilder.Entity("Models.Entities.ConsultingType", b =>
                {
                    b.Navigation("ConsultingTickets");
                });

            modelBuilder.Entity("Models.Entities.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Birds");

                    b.Navigation("ConsultingTickets");

                    b.Navigation("CustomerCertificateDetails");

                    b.Navigation("CustomerLessonDetails");

                    b.Navigation("CustomerOnlineCourseDetails");

                    b.Navigation("CustomerSectionDetails");

                    b.Navigation("CustomerWorkshopClasses");

                    b.Navigation("Feedbacks");

                    b.Navigation("Transactions");

                    b.Navigation("WorkshopAttendances");
                });

            modelBuilder.Entity("Models.Entities.DistancePrice", b =>
                {
                    b.Navigation("ConsultingTickets");
                });

            modelBuilder.Entity("Models.Entities.EntityType", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("TrainerSlots");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Models.Entities.FeedbackType", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("Models.Entities.Lesson", b =>
                {
                    b.Navigation("CustomerLessonDetails");
                });

            modelBuilder.Entity("Models.Entities.OnlineCourse", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("CustomerOnlineCourseDetails");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Models.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Models.Entities.Section", b =>
                {
                    b.Navigation("CustomerSectionDetails");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Models.Entities.Skill", b =>
                {
                    b.Navigation("TrainableSkills");

                    b.Navigation("TrainerSkills");
                });

            modelBuilder.Entity("Models.Entities.Slot", b =>
                {
                    b.Navigation("CenterSlots");

                    b.Navigation("TrainerSlots");
                });

            modelBuilder.Entity("Models.Entities.Trainer", b =>
                {
                    b.Navigation("BirdTrainingProgresses");

                    b.Navigation("BirdTrainingReports");

                    b.Navigation("ConsultingTickets");

                    b.Navigation("TrainerSkills");

                    b.Navigation("TrainerSlots");

                    b.Navigation("WorkshopClassDetails");
                });

            modelBuilder.Entity("Models.Entities.TrainerSlot", b =>
                {
                    b.Navigation("WorkshopClassDetails");
                });

            modelBuilder.Entity("Models.Entities.TrainingCourse", b =>
                {
                    b.Navigation("BirdCertificates");

                    b.Navigation("BirdTrainingCourses");

                    b.Navigation("TrainingCourseSkills");
                });

            modelBuilder.Entity("Models.Entities.TrainingCourseSkill", b =>
                {
                    b.Navigation("BirdTrainingProgresses");
                });

            modelBuilder.Entity("Models.Entities.User", b =>
                {
                    b.Navigation("BirdTrainingCourses");

                    b.Navigation("Customers");

                    b.Navigation("Trainers");
                });

            modelBuilder.Entity("Models.Entities.Workshop", b =>
                {
                    b.Navigation("WorkshopClasses");
                });

            modelBuilder.Entity("Models.Entities.WorkshopClass", b =>
                {
                    b.Navigation("CustomerWorkshopClasses");

                    b.Navigation("WorkshopAttendances");

                    b.Navigation("WorkshopClassDetails");
                });

            modelBuilder.Entity("Models.Entities.WorkshopPricePolicy", b =>
                {
                    b.Navigation("Workshops");
                });

            modelBuilder.Entity("Models.Entities.WorkshopRefundPolicy", b =>
                {
                    b.Navigation("Workshops");
                });
#pragma warning restore 612, 618
        }
    }
}
